### ISSUE TITLE
Underscore in pattern creates an unresolved reference

### ISSUE THREAD

**Issue by MvanWieringen** [lnoor/sphinx-jsonschema#11]
{
    "title": "title",
    "description": "description.",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "mailbox": {
            "description": "Full address of the mailbox localpart@example.com",
            "type": "string",
            "format": "email"
        },
        "recipients": {
            "description": "List of email addresses to which incoming mail is forwarded.",
            "type": "array",
            "items": {
                "type": "string",
                "format": "email",
                "pattern": "(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)"
            },
            "minItems": 1
        }
    },
    "additionalProperties": false,
    "required": ["mailbox", "recipients"]
}

This schema-pattern creates an unresolved reference because of the included underscore. See attached image.
![unresolved_reference](https://user-images.githubusercontent.com/6730346/28206549-abce7e70-6886-11e7-9a05-d60ecdce437c.png)

**Comment by lnoor** [comment]
Currently all values are parsed for reStructuredText content.
Even when the value should be used verbatim as is the case here.
General solution is to parse only title, description and $ref fields for reStructuredText content.
