### ISSUE TITLE
"no module named 'pointer'"

### ISSUE THREAD

**Issue by choldgraf** [lnoor/sphinx-jsonschema#13]
I can't get this extension to function with sphinx, I think because the `json_pointer` module isn't being installed properly. I `pip` installed it, but AFAIK the module doesn't have a `setup.py` file and isn't python 3 compatible. Am I looking in the wrong place for json_pointer?

**Comment by lnoor** [comment]
pip list tells me:
```
l~$ pip list | grep pointer
json-pointer (0.1.2)
```
But I must add that this is for python 2.7.
I haven't tried to use Spinx with python 3.

I wasn't aware that json-pointer didn't install in python3.
Perhaps I should use another json pointer package.
It will be a while before I get to that though.
To put it crudely,the current implementation solves my problem.

There is a jsonpointer (without a minus) on pypi which also implements rfs 6901.
If that also works with  python27and if you're willing to provide a pull request I will gladly incorporate it in sphinx-jsonschema.

**Comment by choldgraf** [comment]
> To put it crudely,the current implementation solves my problem.
I'm in the same boat in terms of trying to solve a problem :-)

Lemme look into it and I'll open a PR if it makes sense.

**Comment by choldgraf** [comment]
see #14 for a fix!

**Comment by lnoor** [comment]
Thanks for the PR.
And for the yaml PR as well.
This weekend at latest I make time to play with them and create a new release.
Will that be soon enough for you?

**Comment by choldgraf** [comment]
no problem :-)  

there might be merge conflicts after one of them is merged, so lemme know when that happens and I can rebase.

**Comment by lnoor** [comment]
Just created and published a 1.4 version including your work.
Thank you for contributing!

**Comment by choldgraf** [comment]
woot!
