### ISSUE TITLE
Relicense under something more permissible than gplv3?

### ISSUE THREAD

**Issue by asottile** [lnoor/sphinx-jsonschema#16]
This makes this package very difficult to use due to the license attached to it

**Comment by lnoor** [comment]
What is the problem that you encounter?

**Comment by asottile** [comment]
Due to the terms of the gpl license, this library is unusable

**Comment by lnoor** [comment]
How so?
Can you give me an example?
What is it you are trying to do that the license prevents?

**Comment by asottile** [comment]
link the library (by import) into a closed source application

**Comment by lnoor** [comment]
OK I think I understand your problem.
I'm a programmer, not a lawyer, and as far as I can tell you are in the clear as long as you do **not distribute** the combined work.
It is however ok to use the application on your own servers as a 'Cloud' product.

That is why I chose the GPL over the AGPL which  would require you to release the source code in that case as well but the GPL does not.

If this isn't sufficient and you intent to distribute your closed source application it is the LGPL that is required. If this is the case please contact me directly by email to negotiate terms.
Note that I incorporated pull requests from others which also need to consent to relicencing their contributions.

**Comment by asottile** [comment]
Thanks for the explanation @lnoor -- I think for the small number of outside contributors (2) it wouldn't be terribly difficult to come to a consensus on a more permissible license (such as MIT / Apache2 / BSD / etc.).  I'm also a programmer and not in a position to discuss terms, if this is the stance on the license for this software I'll unfortunately need to pick another implementation.
