### ISSUE TITLE
Complement

### ISSUE THREAD

**Issue by diogobaeder** [lnoor/sphinx-jsonschema#19]
This issue is not actually a real issue. It's more of a complement; I just wanted to share that I'm amazed at how useful this library is, and how well it works. I started having to deal with JSONSchema in a project, and, while documenting it, I wanted something to help me generating the schemas and embed them in the documentation, so this library fits like a glove. I installed the dependency, added the extension to the Sphinx configs and voilà!, JSONSchemas available in my docs! Just like that, it **just works**!

Thanks a lot, guys, this project rocks! :-)

(Feel free to close this ticket, I just wanted to share my feelings for your great work.)

**Comment by lnoor** [comment]
Thanks a lot for you kind reaction.
When publishing I never thought it would be so useful to so many different people.
Very gratifying to read your ticket.
