### ISSUE TITLE
Fails to parse valid json files

### ISSUE THREAD

**Issue by starhawking** [lnoor/sphinx-jsonschema#21]
Currently all schema files are loaded in with pyyaml. Yaml does not allow for lines to start with tabs, however lines beginning with whitespace are valid json. 

This causes valid schemas to fail to parse

```
exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yaml/scanner.py", line 257, in fetch_more_tokens
    self.get_mark())
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
```

**Comment by lnoor** [comment]
Thanks for reporting.
There is a new version on pypi that resolves this.
