### ISSUE TITLE
Properly implement /definitions

### ISSUE THREAD

**Issue by lnoor** [lnoor/sphinx-jsonschema#23]
The whole `/definitions` section and references to it is currently disregarded.
The easiest way to implement it is to consider it a special case of the existing `$ref` resolving mechanism.

In order to implement this no changes to the referencing code is necessary.
But we do need to replace the (mostly non-existent) handling of the `/definitions` section.

Most straightforward solution is to treat each key under `definitions` as a new top level schema and call the renderer recursively for each one.
If the subschema is missing `title` and `$$target` entries these should be synthesized and included.

**Comment by TheFrok** [comment]
Hi @lnoor!
Great package, I'm really exited using in in my doc :)

I wanted some tips about how to not display my definitions, as I'm presenting them in different places. I saw somewhere that you recommended moving them to a different file, but I prefer using just one file.

What would you recommend?

Again thank for this package :)

**Comment by lnoor** [comment]
Hi thanks for the compliments!
There is an easy (but ugly) fix. See below.

I'd like to rewrite most of the code.
I created a simple tool for my own use, never thought it would be useful to so many others.
And since I didn't need `definitions` ...

In the mean time, if you change wide_format.py to competely ignore the `definitions` key and its value, then you can display the items in `definitions` one by one by explicitly rendering them.
The result is the same as when the `definition` items where stored in a separate file.

**Comment by TheFrok** [comment]
Thanks, eventually I did something similar. I've put the `definitions` in a differemt object and reconstructed the schema before validation
