### ISSUE TITLE
Error when using the directive

### ISSUE THREAD

**Issue by arcanefoam** [lnoor/sphinx-jsonschema#26]
Seems like some of the YAML additions introduced a bug:

Exception occurred:
  File "../python3.6/site-packages/sphinx-jsonschema/__init__.py", line 108, in ordered_load
    return result
UnboundLocalError: local variable 'result' referenced before assignment

I am guessing there is an exception and hence the result value is never assigned.

**Comment by lnoor** [comment]
Hi thanks for the report.
I guess your analysis is correct.
