### ISSUE TITLE
Support `examples`

### ISSUE THREAD

**Issue by mdornseif** [lnoor/sphinx-jsonschema#27]
Since Draft 7 we have `examples`.

> The examples keyword is a place to provide an array of examples that validate against the schema. This isn’t used for validation, but may help with explaining the effect and purpose of the schema to a reader. Each entry should validate against the schema in which is resides, but that isn’t strictly required. 

Would be nice to have them displayed in the documentation table. too.

**Comment by EvilPuppetMaster** [comment]
I've submitted a PR for this: https://github.com/lnoor/sphinx-jsonschema/pull/28

**Comment by lnoor** [comment]
Thank you for contributing!
I've created a new release including your PR.

**Comment by EvilPuppetMaster** [comment]
Thanks!
