### ISSUE TITLE
relative path has to be specified to include local Schema files that should be in search path

### ISSUE THREAD

**Issue by StefanD986** [lnoor/sphinx-jsonschema#3]
I have a directory structure like follows:
```
project_root
+---doc
|   |   .gitignore
|   |   make.bat
|   |   Makefile
|   |
|   +---build
|   |
|   \---source
|       |   conf.py
|       |   example1.json
|       |   index.rst
|       |   SomeJSONSchemaFile.json
|       |
|       +---_static
|       \---_templates
+---src
```

If I want to include `SomeJSONSchemaFile.json` from folder `source`, I have to give the path as relative to the `doc` directory: `.. jsonschema:: source/SomeJSONSchemaFile.json`

Since I usually can include files in the `source` directory without giving the path to `source`, I would expect that I can do the same with `jsonschema` includes.

**Comment by lnoor** [comment]
Do you have a customized Makefile or make.bat file where you direct to the source directory?

**Comment by StefanD986** [comment]
No, I am using the standard makefile that was generated by sphinx-quickstart. With sphinx-quickstart I configured the project to use separate source and build directories.

Gist of the makefiles: https://gist.github.com/StefanD986/309039f51c6457fa077fbc6885764b92

**Comment by lnoor** [comment]
I now understand why you expect the relative path to start in the source directory.
Looking at it 'from the outside', I would expect the same.
Thanks for bringing it to my attention.

**Comment by lnoor** [comment]
I resolved this by making a relative file reference relative to the source file.
So if in ./source/test.rst you have a line
.. jsonschema schemas/test.json
it would try to access the file ./source/schemas/test.json
