### ISSUE TITLE
Backslash cannot be displayed in html

### ISSUE THREAD

**Issue by johnchenghk01** [lnoor/sphinx-jsonschema#35]
page.rst
```
page
====
.. jsonschema:: sample.json
```

sample.json
```
{
  "type": "string",
  "pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
}
```

It becomes `^(([0-9]{3}))?[0-9]{3}-[0-9]{4}$` in browser.

**Comment by lnoor** [comment]
Thanks for the report.
I've just released a new version on pypi that resolves this issue.
