### ISSUE TITLE
Error when both target is in scheme and quotes in title

### ISSUE THREAD

**Issue by ivysotskyi** [lnoor/sphinx-jsonschema#36]
Installing earlier (1.12) version fixes the problem. So it is introduced in 1.13.

I didn't debug it deeply yet. I have ~40 schemas with linking each others. Looks like work of $ref tag is broken or I have some issue in my schemas.

I can provide more information or try to debug it later.

The full log of the error in console while generating doc:

```
exception:  while parsing a flow mappington.schema
  in "<unicode string>", line 80, column 14:
        "value": {
                 ^
expected ',' or '}', but got '<scalar>'
  in "<unicode string>", line 82, column 214:
     ... Optional: Yes (together with \\"variable\\")"
                                         ^
exception:  while parsing a flow sequenceock_definitions
  in "<unicode string>", line 64, column 19:
          "examples": [
                      ^
expected ',' or ']', but got '<scalar>'
  in "<unicode string>", line 65, column 23:
            " {\\n\\r  \\"type\\": \\"expression\\",\\n\\r ...
                          ^

Exception occurred:
  File "c:\program files\python37\lib\site-packages\jsonpointer.py", line 279, in walk
    raise JsonPointerException("member '%s' not found in %s" % (part, doc))
jsonpointer.JsonPointerException: member 'definitions' not found in {}
The full traceback has been saved in C:\Users\......\AppData\Local\Temp\sphinx-err-can9yg2j.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
"ProjectName: Error during Sphinx run. Check correctness of json schemas. Error code == 2"
```

**Comment by lnoor** [comment]
Hi Ivan,
Can you provide a small sample illustrating the problem?
That will make ik easier to find out what is happening.
Thanks Leo

**Comment by ivysotskyi** [comment]
> Hi Ivan,
> Can you provide a small sample illustrating the problem?
> That will make ik easier to find out what is happening.
> Thanks Leo

I cannot provide all the documentation source code right here. I will try to make small example that reproduces the problem.

**Comment by ivysotskyi** [comment]
I figured out that the issue appearsh if there are both **\"** symbol in **title** and **tagget**.

In my case:
```
{
  "title": "Expressions",
  "definitions": {
    "or": {
      "title": "Boolean \"OR\"",
      "$$target": [
        "#/definitions/or"
      ]
    }
  }
}
```
If you remove target or \" from the title the issue is not reproducible.

Looks like issue is caused by [this commit](https://github.com/lnoor/sphinx-jsonschema/commit/f51b50015ac37d3e37073e1ef28e98bb267869af) when the links are created they **cannot parse titles with quotes**.
