### ISSUE TITLE
Handling of dependencies

### ISSUE THREAD

**Issue by MatinF** [lnoor/sphinx-jsonschema#37]
It looks like this tool would be a great fit for some of our documentation purposes. However, it seems the tool does not currently handle `dependencies`. Is this correct, or is there a way to include these in the output generated by the code?

**Comment by lnoor** [comment]
You are right, `dependencies` is not handled right now.
I just had no need for it.
Now that you ask I will put some time in it to get it to work.
Might take a couple of days though before I can release a new version.

**Comment by lnoor** [comment]
Hi, hope I got it right.
It was a bit tricky.
Let me know if it doesn't work for you.
