### ISSUE TITLE
Empty oneOf, anyOf, allOf

### ISSUE THREAD

**Issue by ivysotskyi** [lnoor/sphinx-jsonschema#38]
Sometimes it is needed to set optional "required". Often it is reflected in schemas like this: 

```
 "anyOf": [
    {
      "required": [ "object_id" ]
    },
    {
      "required": [ "result_id" ]
    }
  ]
```

In documentation it is shown as two empty list elements under "anyOf":
![chrome_SKKnrgo2kG](https://user-images.githubusercontent.com/37252364/81264549-43eff380-904a-11ea-8fc1-d66b73b609e8.png)

**Expected result**: "anyOf", "oneOf", "allOf" and other fields should be hidden if there are only hidden properties under them (like "required").

**Comment by ivysotskyi** [comment]
Hi. Is it fixed in some version or any workaround available? Instead of this behavior we now want to mark in some smart way properties that are conditionally required.

**Comment by lnoor** [comment]
@WouterTuinstra fixed this in his contribution
