### ISSUE TITLE
Failing to parse json does not report an error to sphynx

### ISSUE THREAD

**Issue by Lectem** [lnoor/sphinx-jsonschema#39]
It seems no error is reported by sphynx-build when parsing the json fails.
The exception trace is displayed, but not interpreted by the tool as an error nor a warning.

Installed version 1.15 through pip.

**Comment by lnoor** [comment]
That is correct.
Since it began as a personal tool, i knew the input was valid.
I struggled long and hard with docutils to make this work.

If you know how to generate proper errors I gladly include your contribution.
