### ISSUE TITLE
RFE: Global options for permanently enabling directive flags

### ISSUE THREAD

**Issue by ankostis** [lnoor/sphinx-jsonschema#46]
## The itch
The new flags for auto reference/target & definitions work just fine, no need to fiddle with this extension anymore.  
Thank you!

But now i need to repeat the useful flags allover:
```rst
.. jsonschema:: some_schema.yaml
    :lift_definitions:
    :auto_reference:
    :auto_target:
```
## The scratch
Would it be possible to add an [extension-option](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_config_value) so that we can permanently imply the flags for the directive?

To explain what i mean, adding this code in extension's `setup()` would do the trick
(of course it would also needs changes in the directive's logic when parsing the flags):
```python
setup(app):
    app.add_config_value('jsonschema_default_directive_flags', '', 'env')
    ...
```

And a possible content for the user's `docs/conf.py`would be the space-separated flags to enable
(assuming they are all boolean flags):
```python
jsonschema_default_directive_flags = "lift_definitions auto_reference auto_target"
```
... and the user then could simply write:
```rst
.. jsonschema:: some_schema.yaml
```

Does that make sense?

**Comment by ankostis** [comment]
Btw, the changelog for 1.16 does not list the newly introduced flags.

**Comment by lnoor** [comment]
I see the merit in your idea.
But then I also want to be able to overrule the default setting.
Sometimes you may **not** want ``:auto_target:``.

Perhaps something like a flags object where you can set the default and overrule them when needed?
The option could become:
- :auto_target:  Toggles value
- :auto_target: <boolean> Set to specific state

Like it.
