### ISSUE TITLE
REF: `lift_title` config & directive flag

### ISSUE THREAD

**Issue by ankostis** [lnoor/sphinx-jsonschema#48]
(thanks for #46 :+1:)
I would like this library to copy the logic for controling the inclusion of the `description` of a schema in the table (or the text above it),
with `lift_description`, but for `title` property, with a respective property `lift_title`.

My use case is to embed schema-tables in argument definitions:
```:sphinx
       :param f_up_threshold:
            .. jsonschema:: data-schema.yaml#/properties/f_up_threshold
```
But if the specific property has a title, the rendered result is like this:
![Screenshot from 2020-09-20 16-05-07](https://user-images.githubusercontent.com/501585/93712073-d9080a80-fb5b-11ea-84c0-280a49421e90.png)

While i would like is something simpler, without the section-title beneath the argument, like this:
![image](https://user-images.githubusercontent.com/501585/93711909-a01b6600-fb5a-11ea-8d4f-18e243fb2805.png)

**Comment by ankostis** [comment]
btw, i have patched the code to add table-rows with my custom schema fields (`units`, `tags`).  
Strengthening extensibility, is highly appreciated, that is why i'm sharing this information for providing an aspect to it.

**Comment by lnoor** [comment]
Hi, when embedding the title as a regular field you loose the ability to reference the schema from other parts of your document.
This is because the current code creates an anchor with the heading which can be used by the docutils :ref: generated by $ref.
Would that be acceptable?

BTW how did you include support for ``units`` and ``tags``? Did you create new functions or extended the list of keywords?

**Comment by ankostis** [comment]
#########
## `sphinx-jsonschema` extension
##
jsonschema_options = {
    "lift_title": False,
    "lift_definitions": False,
    "auto_reference": True,
    "auto_target": True,
}

## PATCH `sphinx-jsonschema`
#  to render the extra `units`` and ``tags`` schema properties
#
def _patched_sphinx_jsonschema_simpletype(self, schema):
    """Render the *extra* ``units`` and ``tags`` schema properties for every object."""
    rows = _original_sphinx_jsonschema_simpletype(self, schema)

    if "units" in schema:
        units = schema["units"]
        units = f"``{units}``"
        rows.append(self._line(self._cell("units"), self._cell(units)))
        del schema["units"]

    if "tags" in schema:
        tags = ", ".join(f"``{tag}``" for tag in schema["tags"])
        rows.append(self._line(self._cell("tags"), self._cell(tags)))
        del schema["tags"]

    return rows

**Comment by ankostis** [comment]
Actually the way i used it, inside argument definitions, 
the header element was causing sphinx to complain about malformed content -- headers are not allowed anywhere in sphinx-documented code -- only in `.rst` files.  

In any case, it's a nice automation to have those link-targets, it would be even better if it can be turned off.  

(btw, read my previously posted patch-code from Github, i was to quick to post it, in the email)

**Comment by lnoor** [comment]
Hi, just created lift_title. Just need to update the documentation.
May I add your patch example to the documentation?

I agree it would be very nice if jsonschema became easier to modify.
I'm just not sure how to achieve that.
I think wide_format needs to be rewritten to accommodate that.
E.g. a table where for each jsonschema keyword a render function is defined.
That would allow one to easily replace the default behaviour.
Another option is to derive classes like wide_format from a base and allow methods to be overridden.

**Comment by ankostis** [comment]
Sure!  I pasted in the hope that t might be useful.

**Comment by ankostis** [comment]
I would prefer the "table (hook)" apoproach for extension, AND to refactor wide_format,
to make it a little easier to extend, if the need arises.  At the same time, the hardest part was to import the package (see the import-trick) due to a package name with dash.
