### ISSUE TITLE
Problem in 1.16.4-5; producing LaTex Output

### ISSUE THREAD

**Issue by temcdrm** [lnoor/sphinx-jsonschema#52]
Hi - I can do **make html** but **make latex** fails with message as shown below.  The JSON file is here: https://github.com/pnnl/tesp/blob/develop/doc/tso_schema.json and it's referenced just like `.. jsonschema:: tso_schema.json`

This had been producing both HTML and PDF on ReadTheDocs, but then the triggered builds began to fail.  I just checked the JSON file on [jsoneditoronline.org](https://jsoneditoronline.org/), and it seems okay.  For now, I can work around this issue by using version 1.16.3.

Error after **make latex** using either 1.16.4 or 1.16.5
`
Exception occurred:
  File "/home/tom/.local/lib/python3.6/site-packages/sphinx/writers/latex.py", line 947, in <listcomp>
    underlined = [cell.row + cell.height == self.table.row + 1 for cell in cells]
AttributeError: 'NoneType' object has no attribute 'row'
The full traceback has been saved in /tmp/sphinx-err-_pnasj_l.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'latex' failed
make: *** [latex] Error 2
`

**Comment by lnoor** [comment]
Just to let you know I'm looking into it.
Found the smallest sample that displays the problem:

```
.. jsonschema::

    {
        "title": "TSO simplified",
        "type": "object",
        "properties": {
            "anarray": {
                "type": "array",
                "items": [
                    {
                        "type": "number",
                        "enum": [1, 2, 3]
                    }
                ]
            }
        }
    }
```

`items` must be an array for the issue to happen, when `items` is a subschema it works fine.
