### ISSUE TITLE
Renders "null" default value as "None"

### ISSUE THREAD

**Issue by nijel** [lnoor/sphinx-jsonschema#53]
It is confusing that the following snippet:

```
        "dashboard_component_list": {
          "$id": "#root/profile/dashboard_component_list",
          "title": "Default component list",
          "anyOf": [{ "type": "null" }, { "type": "integer" }],
          "default": null
        }
```

Is rendered as:

![image](https://user-images.githubusercontent.com/212189/104012815-c0763b80-51b0-11eb-9621-f4d157015e41.png)

There is no "None" type in JSON, it's Python way of calling it, and we're documenting JSON here, so "null" should be used instead to describe it.

The full schema:

https://github.com/WeblateOrg/weblate_schemas/blob/ffab5fd8e478ef2116591f0280583882831a372a/weblate_schemas/schemas/weblate-userdata.schema.json#L160

Rendered:

https://docs.weblate.org/en/latest/contributing/schemas.html#weblate-user-data-export

**Comment by lnoor** [comment]
Thank  your for reporting this issue.
There is a new version on pypi resolving it.
