### ISSUE TITLE
Hide some properties

### ISSUE THREAD

**Issue by ivysotskyi** [lnoor/sphinx-jsonschema#54]
Some properties in JSON-schemas are useful for JSON schema validation but are completely useless when placed to sphinx documentation. For example, I'd like to have the possibility to hide property "type" for all schemas in documentation because in my case it is always "object" and this only confuses documentation users.

**Comment by lnoor** [comment]
Hi Ivan,
I can imagine this becomes a option to the directive.
But I think it should allow to be more restrictive than just hide the property unconditionally.
You may want to show "type" for strings or number, but not for "object".

Are you willing to create a pull request?
regards,
Leo

**Comment by ivysotskyi** [comment]
maybe it worth implementing some tag like this?
`"$$hide_properties": ["type", "operation_type"]`
Then it will be possible to insert it in some schemas where some properties are unwanted.

Yes, I will implement this later but first, let's agree about implementation detail.

**Comment by lnoor** [comment]
Interresting!
I hadn't considered adding it to the schema itself.

What about: `$$hide_properties": { "type": ["object", "array"]}` would hide "type" when its value is either "object" or "array".

Unless you want to restrict the use of $$hide_properties to the top-level it also means that $$hide_properties works recursively.
So at a lower level you can re-specify what should be hidden or shown.

I suppose that in that case $$hide_properties should become additive. I mean toplevel hides type:object, lower down in a subtree type:array is also hidden, but once outside that subtree type:array is shown again. An empty array (`$$hide_properties": {"type": [])` would allow all to be displayed again.

What are your thoughts?

**Comment by shaded-enmity** [comment]
@lnoor I've evaluated both JSON Pointer (https://datatracker.ietf.org/doc/html/rfc6901) and JSON Path (https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/blob/main/draft-ietf-jsonpath-base.md) and neither really fit the use case.

Both implementations suffer from not being able to get the `parent` of a particular key, so while I could technically do something like `jsonpointer.set('/some/path', None)` which more or less translates to `document['some']['path'] = None` what I'm really looking for is `del document['some']['path']`.

JSON Pointer also doesn't support wildcards, so you'd still need to do some pre-processing of the incoming schema to detect the concrete paths to hide - which for me kind of defeats the point.

Let me open a draft PR later today with my implementation (it's roughly 80 lines including comments), and let's see how you feel about it.
