### ISSUE TITLE
Relative paths don't work inside sphinxcontrib.autohttp.flask docstrings

### ISSUE THREAD

**Issue by JoeWallis-Sopro** [lnoor/sphinx-jsonschema#58]
To quickly and easily build REST documentation for my Flask site I'm using [`sphinxcontrib.autohttp.flask`](https://sphinxcontrib-httpdomain.readthedocs.io/en/stable/#module-sphinxcontrib.autohttp.flask). To document the JSON parts of the REST API I'm using your project.

I store examples and the schemas in the same folder under `schemas` and whilst `literalinclude` works your `jsonschema` doesn't.

1.  Install your package ([`sphinx-jsonschema`](https://pypi.org/project/sphinx-jsonschema/)), [`sphinxcontrib-httpdomain`](https://pypi.org/project/sphinxcontrib-httpdomain/) and Sphinx<4.0.0.
2.  Configure the `conf.py`:
     ```python
    extensions = [
        ...,
        "sphinxcontrib.httpdomain",
        "sphinxcontrib.autohttp.flask",
        "sphinx-jsonschema",
    ]
     ```
3.  Symlink `docs/path/to/folder/schemas` to `src/path/to/folder/schemas`.
4.  Run Sphinx.

```rst
..  automodule:: path.to.folder
```
```python
"""
..  autoflask:: path.to.folder:app
    :undoc-static:
"""

...

@app.route("/post", methods=["POST"])
def post():
    pass


PWD = pathlib.Path(__file__).parent
post.__doc__ = f"""
Test site to run unit and performance tests against.

..  works
..  literalinclude:: /path/to/folder/schemas/post_request.json

..  works
..  literalinclude:: schemas/post_request.schema.json

..  works (but I have to manully set ``__doc__`` as f-doc-strings aren't a thing)
..  jsonschema:: {PWD}/schemas/post_request.schema.json

..  doesn't work
..  jsonschema:: schemas/post_request.schema.json
"""
```

**Note**: Providing the absolute path you're trying to read from would be helpful for end users.

```
/path/to/folder/file.rst: WARNING: "jsonschema" directive encountered an IOError while loading file: schemas/post_request.schema.json
[Errno 2] No such file or directory: 'schemas/post_request.schema.json'
```

**Comment by lnoor** [comment]
Hi, needed to check the source.
The error already produces the full path ([see here](https://github.com/lnoor/sphinx-jsonschema/blob/9848d7a955efc82924272c7b319ac025e7a3d495/sphinx-jsonschema/__init__.py#L165)).
Are you using the latest (1.16.8) version?

**Comment by JoeWallis-Sopro** [comment]
Hi yes, I'm on 1.16.8.

Here's an MVCE to mimic my environment:

`docs/source/conf.py`
```python
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).absolute().parent.parent.parent))

extensions = [
    "sphinx.ext.autodoc",
    "sphinxcontrib.httpdomain",
    "sphinxcontrib.autohttp.flask",
    "sphinx-jsonschema",
]
```

`docs/source/index.rst`
```rst
Example
=======

..  automodule:: example

```

`example/example.schema.json`
```json
{
    "$schema": "http://json-schema.org/schema",
    "type": "object"
}
```

`example/__init__.py`
```python
"""
..  literalinclude:: example.schema.json

..  jsonschema:: example.schema.json

..  literalinclude:: missing.schema.json

..  jsonschema:: missing.schema.json

..  autoflask:: example:app
    :undoc-static:
"""

import pathlib

import flask

app = flask.Flask(__name__)


@app.route("/post", methods=["POST"])
def post():
    pass


PWD = pathlib.Path(__file__).parent
post.__doc__ = f"""
..  literalinclude:: /example.schema.json

..  literalinclude:: example.schema.json

..  jsonschema:: {PWD}/example.schema.json

..  jsonschema:: example.schema.json
"""
```

To build the environment:

```shell
mkdir test
cd test
python -m virtualenv venv
venv/bin/python -m pip install flask "Sphinx<4.0.0" sphinx-jsonschema sphinxcontrib-httpdomain
venv/bin/python -m pip freeze | grep "sphinx-jsonschema"
vim docs/source/conf.py
vim docs/source/index.rst
vim example/__init__.py
vim example/example.schema.json
ln -s "$PWD/example/example.schema.json" "$PWD/docs/source/example.schema.json"
venv/bin/sphinx-build -a -b html docs/source docs/html
```

Output:

```
Collecting ...
...
Installing collected packages: ...
sphinx-jsonschema==1.16.8
Running Sphinx v3.5.4
...
/example/__init__.py:docstring of example:5: WARNING: Include file '/docs/source/missing.schema.json' not found or reading it failed
/example/__init__.py:docstring of example:7: WARNING: "jsonschema" directive encountered an IOError while loading file: /example/missing.schema.json
[Errno 2] No such file or directory: '/example/missing.schema.json'
/example/__init__.py:docstring of example:7: WARNING: "jsonschema" directive encountered an IOError while loading file: example.schema.json
[Errno 2] No such file or directory: 'example.schema.json'
...
```

Notice how `missing.schema.json` is correctly seen as missing. However `example.schema.json` is a relative path not an absolute path.

**Comment by lnoor** [comment]
Hi, sorry it took some time before I could look into it.
Thank you for the elaborate example.
I duplicated your setup but added captions to `__init__.py` to indicate the source of the output.

There are two things that stood out:
First of all my error messages are slightly different:
```/home/leo/src/sphinx-jsonschema/bugreport/example/__init__.py:docstring of example:11: WARNING: Include file '/home/leo/src/sphinx-jsonschema/bugreport/docs/source/missing.schema.json' not found or reading it failed
/home/leo/src/sphinx-jsonschema/bugreport/example/__init__.py:docstring of example:15: WARNING: "jsonschema" directive encountered an IOError while loading file: /home/leo/src/sphinx-jsonschema/bugreport/example/missing.schema.json
[Errno 2] No such file or directory: '/home/leo/src/sphinx-jsonschema/bugreport/example/missing.schema.json'
/home/leo/src/sphinx-jsonschema/bugreport/example/__init__.py:docstring of example:15: WARNING: "jsonschema" directive encountered an IOError while loading file: example.schema.json
[Errno 2] No such file or directory: 'example.schema.json'
```

As you can see the first errors, produced by `missing.schema.json` do show the complete path.
I find it remarkable that your output doesn't.
Secondly, the last error doesn't.

This leads me to believe that flask (and maybe sphinx' own autodoc) do not provide the full path to `sphinx-jsonschema`.

In `__init__.py` in the function `from_file` the document location is determined by ``        document_source = os.path.dirname(self.state.document.current_source)
`` where the relative path to the schema is appended to.
`self.state.document.current_source` refers to the .rst document, perhaps it is not set when using autodoc or similar.

For completeness sake I include my freeze output:
```leo@obelix2:~/src/sphinx-jsonschema/bugreport$ venv/bin/python3 -m pip freeze
alabaster==0.7.12
Babel==2.9.1
certifi==2020.12.5
chardet==4.0.0
click==8.0.1
docutils==0.16
Flask==2.0.1
idna==2.10
imagesize==1.2.0
itsdangerous==2.0.1
Jinja2==3.0.1
jsonpointer==2.1
MarkupSafe==2.0.1
packaging==20.9
Pygments==2.9.0
pyparsing==2.4.7
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
six==1.16.0
snowballstemmer==2.1.0
Sphinx==3.5.4
sphinx-jsonschema==1.16.8
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-httpdomain==1.7.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
urllib3==1.26.4
Werkzeug==2.0.1```

It may be worhwhile to figure out why your setup doesn't show the full path of `missing.schema.json`.
As for the missing path in autodoc, I'm afraid that is outside the scope of this project.
And, frankly, I cannot spare the time to pursue that.

I you find out how sphinx-jsonschema can work nicely with autodoc and/or flask.
Please let me know through a PR or issue and I'm happy to fix it.

**Comment by lnoor** [comment]
Update on my previous post:
In the error message I included the contents of `self.state.document.current_source` and it shows this:
```/home/leo/src/sphinx-jsonschema/bugreport/example/__init__.py:docstring of example:11: WARNING: Include file '/home/leo/src/sphinx-jsonschema/bugreport/docs/source/missing.schema.json' not found or reading it failed
/home/leo/src/sphinx-jsonschema/bugreport/example/__init__.py:docstring of example:15: WARNING: "jsonschema" directive encountered an IOError while loading file: /home/leo/src/sphinx-jsonschema/bugreport/example/missing.schema.json
[Errno 2] No such file or directory: '/home/leo/src/sphinx-jsonschema/bugreport/example/missing.schema.json'(/home/leo/src/sphinx-jsonschema/bugreport/example)
/home/leo/src/sphinx-jsonschema/bugreport/example/__init__.py:docstring of example:15: WARNING: "jsonschema" directive encountered an IOError while loading file: example.schema.json
[Errno 2] No such file or directory: 'example.schema.json'()
```
which clearly shows that `self.state.document.current_source` is indeed empty.

**Comment by JoeWallis-Sopro** [comment]
Thank you for taking the time to verify the bug.

> It may be worhwhile to figure out why your setup doesn't show the full path of `missing.schema.json`.

I wrote my example under root (`/`), so our paths are indeed identical here. (I prefer having short easy to read paths, maybe I should have used `/.../` instead)

> In the error message I included the contents of `self.state.document.current_source` and it shows this: ... which clearly shows that `self.state.document.current_source` is indeed empty.

Would falling back to searching from the `.rst` (rather than the `.py` file) be an option if the path doesn't exist? So if the path doesn't exist your code functions the same as `literalinclude`.

---

I'm thinking the origin of the bug is not because of your code. Thank you for taking the time to look through your side.

**Comment by lnoor** [comment]
> Would falling back to searching from the `.rst` (rather than the `.py` file) be an option if the path doesn't exist? So if the path doesn't exist your code functions the same as `literalinclude`.

Unfortunately there is no `.rst` file.
As you may have noticed the first reference to `example.schema.json` in the docstring at the top of `__init__.py` does render correctly. So at that moment the current_source is set and correct.
It fails in the docstring for the `post` function.
So for some reason current_source is not set there.

Oh, I'm sorry you are referring to your `docs/source/index.rst` calling `automodule:: example`.
That might work somewhat but I'm somewhat uncomfortable with that approach.
I would have to 'unwind the stack' into Sphinx or Docutils controlled objects.
It would also make it unclear what file to use as reference (but, granted, at least some would work).

The best solution is that current_source is properly set.
