### ISSUE TITLE
sphinx-jsonschema (un)safe for parallel processing?

### ISSUE THREAD

**Issue by rspielmann** [lnoor/sphinx-jsonschema#59]
Building documentation with Sphinx 4.0.1 and sphinx-jsonschema 1.16.8 always yields the following warnings:

<pre>WARNING: the sphinx-jsonschema extension does not declare if it is safe for parallel reading, assuming it
         isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read</pre>

This is problematic when sphinx-build is run with the -W flag because in turn, all builds will fail even if there are no "actual" warnings. Is there any way to get around this warning? Would it be an option for the maintainer(s) to declare what the first warning demands?

**Comment by lnoor** [comment]
As far as I can tell the extension is safe for parallel read and marked as such.
Thanks for reporting this issue.
I will release a new version soon.

**Comment by rspielmann** [comment]
> As far as I can tell the extension is safe for parallel read and marked as such.

Nice!

> Thanks for reporting this issue.

You're welcome!

> I will release a new version soon.

Thanks! :)

**Comment by lnoor** [comment]
Fyi: A new version is available on pypi.
