### ISSUE TITLE
pdb.set_trace() in dependencies code

### ISSUE THREAD

**Issue by CrackerJackMack** [lnoor/sphinx-jsonschema#62]
https://github.com/lnoor/sphinx-jsonschema/commit/4e5720d409b513cd39469600f074d77d072eed01#diff-cee3c1b9d63a448621f7a6ad95847a43ea1e76c117cde07cd3c32c0fb486d8beR266

Looks like it was left in there by accident and shouldn't be there anymore.

**Comment by lnoor** [comment]
Good catch, that really shouldn't be there.
Even though everything should keep working, I will create a new release resolving this.
