### ISSUE TITLE
Is it possible to have a table of contents and a separate page for each object?

### ISSUE THREAD

**Issue by red8888** [lnoor/sphinx-jsonschema#67]
I like how this tool creates a table of contents and organizes object: https://github.com/adobe/jsonschema2md

Is it possible to get similar behavior with this extension?

**Comment by lnoor** [comment]
Partly.
The two tools have different use cases. From the documentation Adobe's tool generates self contained markdown whereas sphinx-jsonschema is meant to include schema fragments inside your restructuredtext document by rendering the schema fragment as a restructuredtext table which is embedded with the rest of your document.

However the title attribute generates a restructuredtext section.
Depending on your settings the section references can be included in page level ToC or the global ToC.
Additionally, using the restructuredtext directives the sections can be included in the index.

But sphinx-jsonschema will never be a stand-alone tool like jsonschema2md.

**Comment by red8888** [comment]
"Depending on your settings the section references can be included in page level ToC or the global ToC."

Is there an example of what that config might look like? I have a big schema and was hoping to use this to create docs from it (so not just fragments). Sorry if this is just standard sphinx config stuff I'm new to sphinx in general.

Would I be able to do something like add title attributes and then in my rst loop over all of them to create separate pages? 

Thanks!

**Comment by lnoor** [comment]
The global ToC has a property that controls the depth of sections included on the index page.
```
.. toctree::
    :maxdepth: 2
```
You can increase that to include the sections generated by your schemas.
The page ToC will always include the generated sections.

> Would I be able to do something like add title attributes and then in my rst loop over all of them to create separate pages?
rst is not a programming language. It doesn't have loops.
You might be able to progammatically generate the rst files that sphinx processes in python as a step in the build process.
When you're willing to take that route anything (well almost) is possible.

If all that is a bit too much then perhaps the tool you found may suit you better.
