### ISSUE TITLE
Is it possible to include a copy of the schema json file along with the generated docs?

### ISSUE THREAD

**Issue by red8888** [lnoor/sphinx-jsonschema#68]
I'm referencing a full schema file like this:

```
.. inside index.rst
.. jsonschema:: ../myProject/myschema.json
    :lift_description:
    :lift_definitions:
    :auto_target:
    :auto_reference:
```

This schema will also need to be published and it will be referenced in other schemas or accessed by users via some URL. 

It would be really convenient if the sphinx plugin could copy the full schema file to the generated docs and I could reference it in my rsts. So this way the generated docs could also include an authoritative URL to the actual schema itself.

Does the plugin support this? I couldn't find anything in the docs. It didn't seem like it was possible with generic sphinx/rst to copy and reference an arbitrary file.

**Comment by lnoor** [comment]
Nice. I achieved the same in a  different way.
I published the schemas using http.
Then accessing them by having sphinx-jsonschema access the same public url the validator would use.

**Comment by red8888** [comment]
^ hmm that actually sounds preferable. For my environment relying on doc publishing to also host the schema for consumers fits a little better.

If anyone else wants to do this I found getting a permalink in rst docs kind of painful, but someone on SO found a very clever work around with `html_extra_path`:
https://stackoverflow.com/questions/70158364/how-can-i-change-the-file-path-of-files-referenced-via-the-download-role-to-not

**Comment by lnoor** [comment]
Thanks for sharing.
