### ISSUE TITLE
Invalid pattern escaping

### ISSUE THREAD

**Issue by eorbe** [lnoor/sphinx-jsonschema#70]
If I have a schema with a **pattern** containing a escaped backslash like the following:

```json
{
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "An example",
        "id": "http://example.com/schemas/example.json",
        "type": "string",
        "pattern": "\\(.+\\)"
    }
```

When building the documentation the following error arises:

```
.... WARNING: "jsonschema" directive encountered a the following error while parsing the data.
 json.decoder.JSONDecodeError: Invalid \escape: line 6 column 19 (char 180)
```

The problem seems to be caused by `sphinx-jsonschema` when it silently converts `\\(` and `\\)` characters sequences to `\\\\(` and `\\\\)` [here](https://github.com/lnoor/sphinx-jsonschema/blob/master/sphinx-jsonschema/__init__.py#L314-L315) which is yielding a wrong-escaped JSON like this:

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "An example",
    "id": "http://example.com/schemas/example.json",
    "type": "string",
    "pattern": "\\\(.+\\\)"
}
```

A possible solution is to use raw strings for the replacements [here](https://github.com/lnoor/sphinx-jsonschema/blob/master/sphinx-jsonschema/__init__.py#L314-L315), like this:

```python
    text = text.replace(r'\\(', r'\\\\(')
    text = text.replace(r'\\)', r'\\\\)')
```

**Comment by lnoor** [comment]
Thank you for reporting and resolving this issue.
I've created and uploaded a new version including your work.
