### ISSUE TITLE
How to handle schema defined in Python code

### ISSUE THREAD

**Issue by GlenNicholls** [lnoor/sphinx-jsonschema#71]
I have an interesting scenario. I have been using [jsonschema](https://pypi.org/project/jsonschema/) to validate YAML configuration files. For reference, I define a python dict like so that I use with jsonschema for validating the config files:

``` python
SCHEMA = {
    <jsonschema stuff here>
}
"""Documentation for SCHEMA that validates X.

<Info about what the schema validates and other important notes, warnings, etc.>

<reST table I define here for the schema which documents attributes, types, and info about them. This is painful>
...
"""
```

I have done it this way for quite a few reasons, but it boils down to being able to document the schema within python as that is my application language and adding comments to the schema itself. 

Implementation details aside, I am looking for a way to use sphinx-jsonschema to generate documentation of this schema. I see the [`.. jsonschema::` directive](https://sphinx-jsonschema.readthedocs.io/en/latest/directive.html) which allows defining the schema in raw text which is very close to what I need. I also need a notes column to describe each attribute in the config file.

My question is how do I get there? Does `.. jsonschema::` support nested directives such that I can do something like this?

```
.. jsonschema::
    .. pprint:: app.schema.SCHEMA
```
Where `pprint` just prints the value of the schema for `jsonschema` to injest?

**Comment by lnoor** [comment]
Thank you for the suggestion.
Given that the json or yaml schema data is turned into a dict before processing it should be relatively simple to add an option to the directive that directly provides the schema as a dict.

The thing to consider is how to get the data into context.
I mean, Sphinx doesn't necessarily read your Python code.
It does that only when using any of the autodoc extensions.

Just a thought:
```
.. jsonschema::
    :data: pkg.file.dict
```
which is turned into `from pkg.file import dict`.
Now the imported data can be passed like data read from a file.
Using this option would sidestep loading the data from a file or inline text.

I think something like the above can be implemented quite easily by including a new method `from_data()` to the code in [get_json_data()](https://github.com/lnoor/sphinx-jsonschema/blob/ccd48870e6daf71c3fc1f1da840907d879df132a/sphinx-jsonschema/__init__.py#L187).
Are you willing to create a PR along these lines?

**Comment by GlenNicholls** [comment]
I see, that doesn't sound too bad. So if I'm understanding correctly, if `data` attribute is present then `from_data` would be called to get this data from a package? In essence, `from_data` would use [`importlib.import_module`](https://docs.python.org/3/library/importlib.html#importlib.import_module)?

**Comment by lnoor** [comment]
Yes I think its quite doable. You understand correctly. And you would have to use `importlib.import_module`.

Later I thought of another approach (still using `from_data()`) in the sense that right now the `jsonschema` directive takes an argument that is either a file `.. jsonschema:: path/to/some/file.json` or an URL `.. jsonschema:: http://host/path/schema.json`.

The code now tests for the presence of the 'http' prefix to decide what import routine to use.
One could extend this scheme to `.. jsonschema:: pgk.sub.file.object` where the presence of the dot(s) denotes a Python package (note that there is at least one dot between file and object).

Functionally they are otherwise identical.
But I kinda like the simplicity and doing away with the `:data:` option.

What do you think?

**Comment by GlenNicholls** [comment]
Looking through the current support, I think that’s be fine although a URL would need to be checked first as there could be `.` characters in the URL

**Comment by lnoor** [comment]
Filenames may also contain '.'.
Perhaps the order should be: file, URL, package.
Things might become simpler when adopting Python's "It's easier to ask for forgivenes than to ask for permission"?
I.e. just try them in order until it does not result in an exception.

**Comment by GlenNicholls** [comment]
I agree, the order you suggest should cover everything. I will open a PR once I start working our internal ticket tracking this.

**Comment by lnoor** [comment]
Looking forward to it.

**Comment by GlenNicholls** [comment]
Can you post instructions for building the docs? I'm getting errors when running `make html` from the `docs` dir.

**Comment by GlenNicholls** [comment]
Sorry for the delay in getting to this. It wasn't a high priority on our board, but I had some cycles today to knock it out.
