### ISSUE TITLE
The prefixItems in the array are ignored

### ISSUE THREAD

**Issue by annetre** [lnoor/sphinx-jsonschema#82]
I try to display the following JSON scheme in the documentation:

{
...
"description" : "Test"
"type": "array",
"prefixItems": [
  { "type": "string" }
],
"items": false
}

The result displays "description", "type" and "items". But fails to display "prefixItems" ((((

**Comment by lnoor** [comment]
The code was written to display draft-4 schemas.
I'm waiting for a stable standard before rewriting the software.
In the mean time I've added support a couple of the new keywords that are basically aliases for existing keywords.

I haven't seen or used "prefixItems" before.
Can it be displayed in the same manner as the regular "items" keyword?

**Comment by annetre** [comment]
Thank you.
Yes, I've modified the scheme. Works good.
