### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by liebsc21** [lnoor/sphinx-jsonschema#84]
In my project I receive ``Could not import extension sphinx_jsonschema (exception: No module named 'sphinx_jsonschema')`` from sphinx-build even though the module is installed.

In a minimal setup in which I just installed sphinx-jsonschema in a venv and ``import sphinx_jsonschema``, I receive the same error.

I installed version 1.19.1 and use Python 3.10.

However, it works, when I go into my `site-packages` directory and replace every ``sphinx-jsonschema`` with ``sphinx_jsonschema``.

Why does it not work from scratch?

**Comment by lnoor** [comment]
You should be using `sphinx-jsonschema` not `sphinx_jsonschema`, see the [documentation](https://sphinx-jsonschema.readthedocs.io/en/latest/installation.html)

If that doesn't help please provide me with minimal versions of
- requirements.txt
- conf.py
- index.rst
demonstrating the problem you are facing.

The requirements file should be complete enough to create a venv so it should include sphinx and sphinx-jsonschema.

**Comment by liebsc21** [comment]
I can't reproduce the problem. Sorry the spam.
